apiVersion: v2
appVersion: 1.0.0
description: Common helm library
home: https://github.com/technicaldomain/helm
type: library
maintainers:
  - email: alex@kharkevich.org
    name: Alexander Kharkevich
name: common
version: 2.1.3
