apiVersion: v2
name: ingress
version: 1.1.5
description: A Helm chart for Ingress
type: application
home: https://github.com/technicaldomain/helm
sources:
  - https://github.com/technicaldomain/helm
maintainers:
  - email: alex@kharkevich.org
    name: Alexander Kharkevich
icon: file://icon.png
appVersion: "1.0"

dependencies:
  - name: common
    repository: https://technicaldomain.github.io/helm/
    version: 2.1.4
